// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {main} from '../models';
import {config} from '../models';

export function Activate(arg1:string):Promise<void>;

export function BulkGetCID(arg1:Array<domain.CIDRequest>):Promise<Record<string, domain.PersonResult>>;

export function CheckDatabaseConnection():Promise<boolean>;

export function CheckUpdate(arg1:string):Promise<main.UpdateInfo>;

export function DownloadUpdate(arg1:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetHardware():Promise<string>;

export function GetPassword():Promise<string>;

export function GetVersion():Promise<string>;

export function HasConfig():Promise<boolean>;

export function HasVerifyLicense():Promise<boolean>;

export function InstallUpdate():Promise<void>;

export function Login(arg1:string,arg2:string):Promise<domain.User|string>;

export function OpenExcel():Promise<domain.ExcelResponse>;

export function SaveConfig(arg1:config.Config):Promise<string>;

export function SaveExcelWithDialog(arg1:string):Promise<void>;

export function SavePassword(arg1:string):Promise<string>;

export function TestConnection(arg1:config.Config,arg2:string):Promise<string>;

export function UpdateExcelStatus(arg1:Array<Record<string, any>>):Promise<void>;
