// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Activate(arg1) {
  return window['go']['main']['App']['Activate'](arg1);
}

export function BulkGetCID(arg1) {
  return window['go']['main']['App']['BulkGetCID'](arg1);
}

export function CheckDatabaseConnection() {
  return window['go']['main']['App']['CheckDatabaseConnection']();
}

export function CheckUpdate(arg1) {
  return window['go']['main']['App']['CheckUpdate'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHardware() {
  return window['go']['main']['App']['GetHardware']();
}

export function GetPassword() {
  return window['go']['main']['App']['GetPassword']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HasConfig() {
  return window['go']['main']['App']['HasConfig']();
}

export function HasVerifyLicense() {
  return window['go']['main']['App']['HasVerifyLicense']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function OpenExcel() {
  return window['go']['main']['App']['OpenExcel']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveExcelWithDialog(arg1) {
  return window['go']['main']['App']['SaveExcelWithDialog'](arg1);
}

export function SavePassword(arg1) {
  return window['go']['main']['App']['SavePassword'](arg1);
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}

export function UpdateExcelStatus(arg1) {
  return window['go']['main']['App']['UpdateExcelStatus'](arg1);
}
